import type { Metadata } from 'next';
import '~/styles/globals.css';

export const metadata: Metadata = {
  title: 'Chacha',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">{children}</body>
    </html>
  );
}
